(async()=>{
'use strict';
const root=document.querySelector('[data-post-detail-root]'),toast=document.querySelector('[data-toast]'),api=window.LimbusCommunity;
const normalizeLegacyIdentityName=value=>String(value??'').replace(/蜘蛛の巣 (薬指|親指|中指|小指)の子分/g,'蜘蛛の巣 $1の子方');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const showToast=message=>{toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600)};
const themeRoot=document.documentElement;const applyTheme=t=>{themeRoot.dataset.theme=t;document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.setAttribute('aria-pressed',String(t==='dark')))};applyTheme(localStorage.getItem('limbus-theme')||'light');document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.onclick=()=>{const n=themeRoot.dataset.theme==='dark'?'light':'dark';applyTheme(n);localStorage.setItem('limbus-theme',n)});
const params=new URLSearchParams(location.search);const id=params.get('id');const source=params.get('from');const backHref=source==='bookmarks'?'bookmarks.html':source==='my-posts'?'my-posts.html':'index.html#community';const backLabel=source==='bookmarks'?'← ブックマーク一覧へ戻る':source==='my-posts'?'← 自分の投稿へ戻る':'← 投稿一覧に戻る';document.querySelectorAll('.detail-back-action,.detail-mobile-back').forEach(a=>{a.href=backHref;a.textContent=backLabel});
try{
 let post,profile;
 if(!id)throw new Error('not-found');
 const cloud=await api?.getCloudPost(id);
 if(cloud){const countedViews=await api.registerPostView(cloud.id);const c=cloud.content||{};post={id:cloud.id,title:cloud.title,summary:cloud.summary,category:cloud.category==='mirror_dungeon'?'鏡ダンジョン':cloud.category,difficulty:cloud.difficulty==='HARD'?'ハード':cloud.difficulty==='NORMAL'?'ノーマル':cloud.difficulty||'',type:cloud.strategy_type||'',published:cloud.published_at||cloud.created_at,updated:cloud.updated_at,views:Number.isFinite(countedViews)?countedViews:(cloud.views||0),likes:cloud.likes||0,keywords:c.keywords||[],tags:c.tags||[],selectedIdentities:c.selectedIdentities||[],party:c.party||[],egos:c.egos||[],themePacks:c.themePacks||[],description:c.description||''};profile=await api.getProfile(cloud.author_id);}
 if(!post)throw new Error('not-found');document.title=`${post.title}｜攻略詳細`;
 const sinnerDisplayOrder=['イサン','ファウスト','ドンキホーテ','良秀','ムルソー','ホンル','ヒースクリフ','イシュメール','ロージャ','シンクレア','ウーティス','グレゴール'];
 const sinnerRank=new Map(sinnerDisplayOrder.map((name,index)=>[name,index]));
 const selectedSource=(post.selectedIdentities||[]).length?post.selectedIdentities:(post.party||[]);
 const selectedParty=[...selectedSource].sort((a,b)=>(sinnerRank.get(a.sinner)??99)-(sinnerRank.get(b.sinner)??99));
 const isFreeIdentity=x=>!!x?.is_free||String(x?.identity||'').includes('自由枠');
 const sinnerNumber=x=>String(x?.sinner_id||({'イサン':'01','ファウスト':'02','ドンキホーテ':'03','良秀':'04','ムルソー':'05','ホンル':'06','ヒースクリフ':'07','イシュメール':'08','ロージャ':'09','シンクレア':'11','ウーティス':'12','グレゴール':'13'}[x?.sinner]||'--')).padStart(2,'0');
 const identities=selectedParty.map(x=>{const image=window.LimbusIdentityImages?.forIdentity?.(x.sinner,x.identity,{free:isFreeIdentity(x)});return `<article class="detail-identity-card ${isFreeIdentity(x)?'is-free':''}${image?' has-identity-image':''}"${image?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.88)),url('${esc(image)}')"`:''}><span>${esc(sinnerNumber(x))}</span><strong>${esc(x.sinner)}</strong><small>${esc(isFreeIdentity(x)?'自由枠（誰でも可）':normalizeLegacyIdentityName(x.identity))}</small></article>`;}).join('');
 const alternatives=selectedParty.filter(x=>(x.alternatives||[]).length).map(x=>`<article class="detail-substitute-card"><b>${esc(sinnerNumber(x))} ${esc(x.sinner)}の代用</b><div>${x.alternatives.map(name=>`<span>${esc(normalizeLegacyIdentityName(name))}</span>`).join('')}</div></article>`).join('');
 const formation=[...(post.party||[])].sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)).map(x=>{const image=window.LimbusIdentityImages?.forIdentity?.(x.sinner,x.identity,{free:isFreeIdentity(x)});return `<article class="detail-party-card ${isFreeIdentity(x)?'is-free':''}${image?' has-identity-image':''}"${image?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.88)),url('${esc(image)}')"`:''}><span>${String(x.order||'--').padStart(2,'0')}</span><strong>${esc(x.sinner)}</strong><small>${esc(isFreeIdentity(x)?'自由枠（誰でも可）':normalizeLegacyIdentityName(x.identity))}</small></article>`;}).join('');
 const egos=(post.egos||[]).length?post.egos.map(g=>`<article class="detail-ego-card"><strong>${esc(g.sinner)}</strong><ul>${(g.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join(''):'<p class="detail-empty">使用E.G.Oは設定されていません。</p>';
 const packs=(post.themePacks||[]).length?post.themePacks.map(x=>`<span class="detail-pack-chip"><b>${x.floor}F</b>${esc(x.name)}</span>`).join(''):'<p class="detail-empty">進行テーマパックは設定されていません。</p>';
 root.innerHTML=`<article class="post-detail-article"><header class="post-detail-hero"><div class="detail-badges"><span>${esc(post.category)}</span><span>${esc(post.difficulty)}</span><span>${esc(post.type)}</span></div><div class="detail-title-row"><div><p class="section-kicker">STRATEGY DETAIL</p><h1>${esc(post.title)}</h1></div></div><p class="post-detail-summary">${esc(post.summary)}</p><div class="detail-author-card">${api.authorMarkup(profile)}<a class="post-detail-link" href="${profile.id==='admin-m'?'index.html#community':`profile.html?id=${encodeURIComponent(profile.id)}`}">投稿者を見る</a></div><div class="detail-meta"><span>閲覧 ${Number(post.views||0).toLocaleString('ja-JP')}</span><button type="button" class="detail-like-button" data-detail-like><span aria-hidden="true">♥</span><b data-detail-like-count>${Number(post.likes||0).toLocaleString('ja-JP')}</b></button><span>投稿日 ${String(post.published||'').slice(0,10)}</span></div><div class="detail-tag-row">${[...(post.keywords||[]),...(post.tags||[])].map(x=>`<span>${esc(x)}</span>`).join('')}</div></header><section class="detail-section"><div class="detail-section-title"><small>SELECTED IDENTITIES</small><h2>使用人格</h2></div><div class="detail-identity-grid">${identities}</div></section>${alternatives?`<section class="detail-section"><div class="detail-section-title"><small>SUBSTITUTE IDENTITIES</small><h2>代用人格 <em>任意</em></h2></div><div class="detail-substitute-grid">${alternatives}</div></section>`:''}<section class="detail-section"><div class="detail-section-title"><small>PARTY ORDER</small><h2>編成順</h2></div><div class="detail-party-grid">${formation}</div></section><section class="detail-section"><div class="detail-section-title"><small>E.G.O</small><h2>装備E.G.O</h2></div><div class="detail-ego-grid">${egos}</div></section><section class="detail-section"><div class="detail-section-title"><small>THEME PACK ROUTE</small><h2>選択パック</h2></div><div class="detail-pack-list">${packs}</div></section><section class="detail-section detail-description"><div class="detail-section-title"><small>STRATEGY</small><h2>攻略説明</h2></div><p>${esc(post.description||'').replaceAll('\n','<br>')}</p></section></article>`;
 const likeButton=document.querySelector('[data-detail-like]'),likeCount=document.querySelector('[data-detail-like-count]');
 const syncLike=async()=>{const liked=await api.isLiked(post.id);likeButton?.classList.toggle('is-liked',liked);likeButton?.setAttribute('aria-pressed',String(liked));likeButton?.setAttribute('aria-label',liked?'いいねを取り消す':'この攻略にいいねする');};
 await syncLike();if(likeButton)likeButton.onclick=async()=>{const user=await api.sessionUser();if(!user){window.LimbusAuth?.open();return;}likeButton.disabled=true;try{const liked=likeButton.classList.contains('is-liked');const total=await api.setLike(post.id,!liked);likeCount.textContent=Number(total||0).toLocaleString('ja-JP');await syncLike();showToast(liked?'いいねを取り消しました。':'いいねしました。');}finally{likeButton.disabled=false;}};
 const buttons=[...document.querySelectorAll('[data-save-post]')];const currentUser=await api.sessionUser();const ownPost=currentUser?.id===cloud?.author_id;if(ownPost)buttons.forEach(btn=>{btn.disabled=true;btn.classList.add('is-own-post');btn.textContent='🔖 自分の投稿';btn.title='自分の投稿はブックマークできません';});const sync=async()=>{if(ownPost)return;const saved=await api.isBookmarked(post.id);buttons.forEach(btn=>{btn.classList.toggle('is-saved',saved);btn.setAttribute('aria-pressed',String(saved));btn.textContent=saved?'🔖 保存済み':'🔖 ブックマーク'})};await sync();buttons.forEach(btn=>btn.onclick=async()=>{if(ownPost)return;const user=await api.sessionUser();if(!user){window.LimbusAuth?.open();return}const saved=await api.isBookmarked(post.id);await api.setBookmark(post.id,!saved);await sync();showToast(saved?'ブックマークを解除しました。':'ブックマークに保存しました。')});
 const shareDialog=document.querySelector('[data-share-dialog]'),openShare=()=>{shareDialog.hidden=false;requestAnimationFrame(()=>shareDialog.classList.add('is-open'));document.body.classList.add('dialog-open')},closeShare=()=>{shareDialog.classList.remove('is-open');document.body.classList.remove('dialog-open');setTimeout(()=>shareDialog.hidden=true,180)};document.querySelector('[data-open-share]')?.addEventListener('click',openShare);document.querySelector('[data-close-share]')?.addEventListener('click',closeShare);shareDialog?.addEventListener('click',e=>{if(e.target===shareDialog)closeShare()});const shareUrl=location.href,shareText=`${post.title}｜Limbus Company 攻略投稿サイト`;document.querySelector('[data-share-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(shareUrl);closeShare();showToast('URLをコピーしました。')});document.querySelector('[data-share-x]')?.addEventListener('click',()=>window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,'_blank','noopener,noreferrer'));document.querySelector('[data-share-bluesky]')?.addEventListener('click',()=>window.open(`https://bsky.app/intent/compose?text=${encodeURIComponent(`${shareText}\n${shareUrl}`)}`,'_blank','noopener,noreferrer'));
}catch(error){console.error(error);root.innerHTML='<section class="detail-error"><h1>投稿を表示できませんでした</h1><p>投稿が存在しないか、閲覧権限がありません。</p><a class="button button-primary" href="index.html#community">投稿一覧へ戻る</a></section>'}
})();
