(async()=>{
'use strict';
const client=window.limbusSupabase,api=window.LimbusCommunity,qs=(s,r=document)=>r.querySelector(s),form=qs('[data-profile-form]'),content=qs('[data-profile-content]'),loginRequired=qs('[data-profile-login-required]'),notice=qs('[data-profile-notice]'),themeButton=qs('[data-profile-theme]');let user=null,initial=null,previewObjectUrl='';
const targetId=new URLSearchParams(location.search).get('id');
function showNotice(t,state='warning'){if(!notice)return;notice.textContent=t;notice.dataset.state=state;notice.hidden=!t}
const fallbackName=u=>u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email?.split('@')[0]||'ユーザー';
const fallbackAvatar=u=>u?.user_metadata?.avatar_url||u?.user_metadata?.picture||'logo-mark.svg';
const formatDate=v=>v?new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric'}).format(new Date(v)):'―';
const avatarPreview=()=>qs('[data-profile-avatar-preview]');
function safeAvatar(value){const url=String(value||'').trim();return url&&!url.startsWith('blob:')?url:fallbackAvatar(user)}
function setAvatarPreview(src){const image=avatarPreview();if(!image)return;image.onerror=()=>{image.onerror=null;image.src='logo-mark.svg'};image.src=src||fallbackAvatar(user)}
function clearObjectPreview(){if(previewObjectUrl){URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=''}}
function applyPreview(){if(!form)return;qs('[data-profile-name-preview]').textContent=form.display_name.value.trim()||fallbackName(user);const file=form.avatar_file?.files?.[0];if(file){clearObjectPreview();previewObjectUrl=URL.createObjectURL(file);setAvatarPreview(previewObjectUrl)}else setAvatarPreview(safeAvatar(form.avatar_url.value));qs('[data-profile-name-count]').textContent=form.display_name.value.length;qs('[data-profile-bio-count]').textContent=form.bio.value.length}
function validateAvatarFile(file){if(!file)return;const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(!allowed.includes(file.type))throw new Error('アイコン画像はJPG・PNG・WebP・GIFを選択してください。');if(file.size>5*1024*1024)throw new Error('アイコン画像は5MB以下にしてください。')}
async function uploadAvatar(file){validateAvatarFile(file);const ext=({"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"})[file.type]||'img';const path=`${user.id}/avatar.${ext}`;const {error}=await client.storage.from('profile-avatars').upload(path,file,{cacheControl:'3600',upsert:true,contentType:file.type});if(error)throw new Error(`画像をアップロードできませんでした。Storage設定を確認してください。（${error.message}）`);const {data}=client.storage.from('profile-avatars').getPublicUrl(path);return `${data.publicUrl}?v=${Date.now()}`}
async function refreshFollow(id,readonly){const state=await api.getFollowState(id);qs('[data-profile-following-count]').textContent=state.followingCount;qs('[data-profile-follower-count]').textContent=state.followerCount;const panel=qs('[data-profile-follow-panel]'),btn=qs('[data-profile-follow]');if(panel)panel.hidden=!readonly||!user;if(btn){btn.textContent=state.following?'フォローを解除':'フォローする';btn.classList.toggle('is-following',state.following);btn.onclick=async()=>{btn.disabled=true;try{await api.setFollow(id,!state.following);await refreshFollow(id,readonly);showNotice(state.following?'フォローを解除しました。':'フォローしました。','success')}catch(e){showNotice(e.message==='self-follow'?'自分自身はフォローできません。':e.message,'error')}finally{btn.disabled=false}}}}
async function fill(profile={},readonly=false){const display=profile.display_name||fallbackName(user),avatar=safeAvatar(profile.avatar_url);const adminBadge=qs('[data-profile-admin]');if(adminBadge)adminBadge.hidden=profile.role!=='admin';qs('[data-profile-name-preview]').textContent=display;setAvatarPreview(avatar);qs('[data-profile-email]').textContent=readonly?'公開プロフィール':(user?.email||'');qs('[data-profile-created]').textContent=formatDate(profile.created_at||user?.created_at);const id=profile.id||user?.id;if(client&&id){const {count}=await client.from('posts').select('*',{count:'exact',head:true}).eq('author_id',id).eq('status','published');qs('[data-profile-post-count]').textContent=count||0}await refreshFollow(id,readonly);if(readonly){form.hidden=true;qs('[data-own-profile-stat]')?.setAttribute('hidden','');document.querySelector('.profile-heading p:last-child').textContent=profile.bio||'自己紹介はまだ設定されていません。';return}initial={display_name:display,avatar_url:avatar,bio:profile.bio||''};form.display_name.value=initial.display_name;form.avatar_url.value=profile.avatar_url&&!String(profile.avatar_url).startsWith('blob:')?profile.avatar_url:'';form.bio.value=initial.bio;const {count}=await client.from('bookmarks').select('*',{count:'exact',head:true}).eq('user_id',user.id);qs('[data-profile-bookmark-count]').textContent=count||0;applyPreview()}
if(!client){loginRequired.hidden=false;showNotice('接続設定を読み込めませんでした。','error');return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;const profileId=targetId||user?.id;if(!profileId){loginRequired.hidden=false;return}content.hidden=false;const {data,error}=await client.from('profiles').select('id,display_name,avatar_url,bio,role,created_at').eq('id',profileId).maybeSingle();if(error||!data){showNotice('プロフィールを読み込めませんでした。','error');return}const readonly=profileId!==user?.id;await fill(data,readonly);if(readonly){document.title=`${data.display_name}｜投稿者プロフィール`;qs('.profile-heading h1').textContent='投稿者プロフィール'}
form?.addEventListener('input',e=>{if(e.target?.name==='avatar_url'&&String(e.target.value).trim().startsWith('blob:'))showNotice('blob:で始まるURLは一時URLのため保存できません。画像ファイルを選択してください。','warning');applyPreview()});
form?.addEventListener('submit',async e=>{e.preventDefault();if(!user||profileId!==user.id)return;const display_name=form.display_name.value.trim();if(!display_name)return showNotice('表示名を入力してください。','error');const typedUrl=form.avatar_url.value.trim();if(typedUrl.startsWith('blob:'))return showNotice('blob:で始まる一時URLは保存できません。画像ファイルを選択してください。','error');const saveButton=qs('[data-profile-save]');saveButton.disabled=true;try{const {data:duplicate,error:duplicateError}=await client.from('profiles').select('id').eq('display_name',display_name).neq('id',user.id).limit(1);if(duplicateError)throw duplicateError;if(duplicate?.length)throw new Error('display_name_taken');const file=form.avatar_file?.files?.[0];const avatar_url=file?await uploadAvatar(file):(typedUrl||null);const payload={id:user.id,display_name,avatar_url,bio:form.bio.value.trim()||null,updated_at:new Date().toISOString()};const {error}=await client.from('profiles').upsert(payload,{onConflict:'id'});if(error)throw error;const {data:fresh,error:freshError}=await client.from('profiles').select('display_name,avatar_url,bio,updated_at').eq('id',user.id).single();if(freshError)throw freshError;clearObjectPreview();form.avatar_file.value='';initial={display_name:fresh.display_name||display_name,avatar_url:safeAvatar(fresh.avatar_url),bio:fresh.bio||''};form.avatar_url.value=fresh.avatar_url||'';setAvatarPreview(initial.avatar_url);localStorage.setItem('limbus-profile-updated-at',String(Date.now()));window.dispatchEvent(new CustomEvent('limbus-profile-updated',{detail:{profile:initial}}));showNotice('プロフィールを保存しました。','success')}catch(error){console.error(error);const message=String(error?.message||'');showNotice(message.includes('display_name_taken')||message.includes('duplicate key')?'その表示名はすでに使用されています。別の名前を入力してください。':message.includes('row-level security')?'このアカウントではプロフィールを変更できません。':'プロフィールを保存できませんでした。'+(message?`（${message}）`:''),'error')}finally{saveButton.disabled=false}});
qs('[data-profile-reset]')?.addEventListener('click',()=>{if(!initial)return;clearObjectPreview();form.reset();form.display_name.value=initial.display_name;form.avatar_url.value=initial.avatar_url==='logo-mark.svg'?'':initial.avatar_url;form.bio.value=initial.bio;applyPreview()});
window.addEventListener('beforeunload',clearObjectPreview);
const applyProfileTheme=theme=>{document.documentElement.dataset.theme=theme;const dark=theme==='dark';if(themeButton){themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('aria-label',dark?'ライトモードに切り替える':'ダークモードに切り替える')}};const savedTheme=localStorage.getItem('limbus-theme')||'light';applyProfileTheme(savedTheme);themeButton?.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';applyProfileTheme(next);localStorage.setItem('limbus-theme',next)});
})();
