(()=>{
'use strict';
const WIDTH=1200,HEIGHT=630;
const loadImage=src=>new Promise(resolve=>{if(!src){resolve(null);return;}const image=new Image();image.decoding='async';image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=new URL(src,document.baseURI).href;});
const roundedRect=(ctx,x,y,w,h,r)=>{ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.closePath();};
const cover=(ctx,image,x,y,w,h)=>{const scale=Math.max(w/image.naturalWidth,h/image.naturalHeight),sw=w/scale,sh=h/scale,sx=(image.naturalWidth-sw)/2,sy=(image.naturalHeight-sh)/2;ctx.drawImage(image,sx,sy,sw,sh,x,y,w,h);};
const fitText=(ctx,text,maxWidth,start=30,min=16)=>{let size=start;while(size>min){ctx.font=`800 ${size}px "Yu Gothic",Meiryo,sans-serif`;if(ctx.measureText(text).width<=maxWidth)break;size-=1;}return size;};
async function create({post,profile,party}){
 const canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,WIDTH,HEIGHT);gradient.addColorStop(0,'#11161d');gradient.addColorStop(.62,'#171c23');gradient.addColorStop(1,'#241b10');ctx.fillStyle=gradient;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#d79a20';ctx.fillRect(0,0,WIDTH,8);
 ctx.fillStyle='#e1ad3f';ctx.font='700 17px Georgia,serif';ctx.fillText('LIMBUS COMPANY STRATEGY',32,43);const meta=[post.category,post.difficulty?String(post.difficulty).toUpperCase():'',`SEASON ${post.season||7}`].filter(Boolean).join('  /  ');ctx.fillStyle='#f6ead0';ctx.font='700 18px "Yu Gothic",Meiryo,sans-serif';ctx.textAlign='right';ctx.fillText(meta,1168,43);ctx.textAlign='left';const title=String(post.title||'無題の攻略');fitText(ctx,title,820,38,23);ctx.fillStyle='#fff';ctx.fillText(title,32,94);const author=profile?.display_name||'匿名投稿者',rank=profile?.rank_title||profile?.rank_name||profile?.rank||'';ctx.fillStyle='#c8c2b8';ctx.font='600 17px "Yu Gothic",Meiryo,sans-serif';ctx.fillText(`投稿者  ${author}${rank?`  /  ${rank}`:''}`,34,128);
 const ordered=[...(party||[])].sort((a,b)=>(Number(a.order)||99)-(Number(b.order)||99)).slice(0,12),gap=8,left=30,top=154,cellW=(WIDTH-left*2-gap*5)/6,cellH=211,entries=await Promise.all(Array.from({length:12},async(_,index)=>{const item=ordered[index];if(!item)return {item:null,image:null};const imageUrl=window.LimbusIdentityImages?.forIdentity?.(item.sinner,item.identity,{free:!!item.is_free||String(item.identity||'').includes('自由枠')})||'';return {item,image:await loadImage(imageUrl)};}));
 entries.forEach(({item,image},index)=>{const col=index%6,row=Math.floor(index/6),x=left+col*(cellW+gap),y=top+row*(cellH+gap);ctx.save();roundedRect(ctx,x,y,cellW,cellH,8);ctx.clip();ctx.fillStyle='#252b34';ctx.fillRect(x,y,cellW,cellH);if(image)cover(ctx,image,x,y,cellW,cellH);const shade=ctx.createLinearGradient(0,y+cellH*.38,0,y+cellH);shade.addColorStop(0,'rgba(0,0,0,0)');shade.addColorStop(1,'rgba(0,0,0,.94)');ctx.fillStyle=shade;ctx.fillRect(x,y,cellW,cellH);ctx.restore();ctx.strokeStyle=item?'#b98a2e':'#3b434e';ctx.lineWidth=2;roundedRect(ctx,x,y,cellW,cellH,8);ctx.stroke();ctx.fillStyle='#e9b949';ctx.font='900 18px Georgia,serif';ctx.fillText(String(index+1).padStart(2,'0'),x+11,y+25);if(item){ctx.fillStyle='#fff';fitText(ctx,item.sinner,cellW-20,20,14);ctx.fillText(item.sinner,x+10,y+cellH-38);ctx.fillStyle='#ddd5c9';fitText(ctx,String(item.identity||''),cellW-20,13,10);ctx.fillText(String(item.identity||''),x+10,y+cellH-15);}else{ctx.fillStyle='#717985';ctx.font='700 14px sans-serif';ctx.fillText('EMPTY',x+10,y+cellH-17);}});ctx.fillStyle='#d79a20';ctx.fillRect(30,HEIGHT-19,1140,1);ctx.fillStyle='#918b82';ctx.font='600 12px sans-serif';ctx.fillText('非公式 Limbus Company 攻略投稿サイト',32,HEIGHT-4);return canvas;
}
const toBlob=canvas=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('image-generation-failed')),'image/png'));
window.LimbusShareCard={create,toBlob};
})();
