(async()=>{
'use strict';
const root=document.querySelector('[data-post-detail-root]'),toast=document.querySelector('[data-toast]'),api=window.LimbusCommunity;
const normalizeLegacyIdentityName=value=>window.LimbusIdentityImages?.normalize?.(String(value??'').replace(/蜘蛛の巣 (薬指|親指|中指|小指)の子分/g,'蜘蛛の巣 $1の子方'))||String(value??'');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const showToast=message=>{toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600)};
const themeRoot=document.documentElement;const applyTheme=t=>{themeRoot.dataset.theme=t;document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.setAttribute('aria-pressed',String(t==='dark')))};applyTheme(localStorage.getItem('limbus-theme')||'light');document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.onclick=()=>{const n=themeRoot.dataset.theme==='dark'?'light':'dark';applyTheme(n);localStorage.setItem('limbus-theme',n)});
const params=new URLSearchParams(location.search);const id=params.get('id');const source=params.get('from');const backHref=source==='bookmarks'?'bookmarks.html':source==='my-posts'?'my-posts.html':`index.html?returnPost=${encodeURIComponent(id||'')}#community`;const backLabel=source==='bookmarks'?'← ブックマーク一覧へ戻る':source==='my-posts'?'← 自分の投稿へ戻る':'← 投稿一覧に戻る';document.querySelectorAll('.detail-back-action,.detail-mobile-back').forEach(a=>{a.href=backHref;a.textContent=backLabel});
try{
 let identityCatalog=[];
 let siteConfig={legacyPostSeason:7};
 try{const siteConfigResponse=await fetch('data/site-config.json?v=1.1.39',{cache:'no-cache'});if(siteConfigResponse.ok)siteConfig=await siteConfigResponse.json();}catch(configError){console.warn('サイト設定を読み込めませんでした。',configError);}
 try{const identityResponse=await fetch('data/identities.json?v=1.1.23',{cache:'no-cache'});if(identityResponse.ok){const identityData=await identityResponse.json();identityCatalog=(Array.isArray(identityData)?identityData:[]).flatMap(group=>(group.identities||[]));}}catch(identityError){console.warn('人格条件データを読み込めませんでした。',identityError);}
 let post,profile;
 if(!id)throw new Error('not-found');
 const cloud=await api?.getCloudPost(id);
 if(cloud){const countedViews=await api.registerPostView(cloud.id);const c=cloud.content||{};post={id:cloud.id,title:cloud.title,summary:cloud.summary,category:cloud.category==='mirror_dungeon'?'鏡ダンジョン':cloud.category,difficulty:cloud.difficulty==='HARD'?'ハード':cloud.difficulty==='NORMAL'?'ノーマル':cloud.difficulty||'',type:cloud.strategy_type||'',season:Number(c.season)||Number(siteConfig.legacyPostSeason)||7,published:cloud.published_at||cloud.created_at,updated:cloud.updated_at,views:Number.isFinite(countedViews)?countedViews:(cloud.views||0),likes:cloud.likes||0,keywords:c.keywords||[],tags:c.tags||[],selectedIdentities:c.selectedIdentities||[],party:c.party||[],egos:c.egos||[],themePacks:c.themePacks||[],description:c.description||''};profile=await api.getProfile(cloud.author_id);}
 if(!post)throw new Error('not-found');document.title=`${post.title}｜攻略詳細`;
 const sinnerDisplayOrder=['イサン','ファウスト','ドンキホーテ','良秀','ムルソー','ホンル','ヒースクリフ','イシュメール','ロージャ','シンクレア','ウーティス','グレゴール'];
 const sinnerRank=new Map(sinnerDisplayOrder.map((name,index)=>[name,index]));
 const selectedSource=(post.selectedIdentities||[]).length?post.selectedIdentities:(post.party||[]);
 const selectedParty=[...selectedSource].sort((a,b)=>(sinnerRank.get(a.sinner)??99)-(sinnerRank.get(b.sinner)??99));
 const isFreeIdentity=x=>!!x?.is_free||String(x?.identity||'').includes('自由枠');
 const sinnerNumber=x=>String(x?.sinner_id||({'イサン':'01','ファウスト':'02','ドンキホーテ':'03','良秀':'04','ムルソー':'05','ホンル':'06','ヒースクリフ':'07','イシュメール':'08','ロージャ':'09','シンクレア':'11','ウーティス':'12','グレゴール':'13'}[x?.sinner]||'--')).padStart(2,'0');
 const identityLookupKey=value=>normalizeLegacyIdentityName(value).replace(/[：:]/g,':').replace(/\s+/g,'').toLowerCase();
 const identityMetaFor=x=>identityCatalog.find(item=>item.sinner===x?.sinner&&identityLookupKey(item.name)===identityLookupKey(x?.identity));
 const identityConditionMarkup=x=>{if(isFreeIdentity(x))return '';const meta=identityMetaFor(x);if(!meta)return '';const conditional=(meta.conditionalKeywords||[]).map(entry=>({keywords:entry.keywords||[],text:entry.conditionLabel||entry.note||'条件を満たした場合に有効'}));const losses=(meta.keywordLossConditions||[]).map(entry=>({keywords:entry.keywords||[],text:`${entry.conditionLabel||'指定スキルを交換した場合'} → ${(entry.keywords||[]).join('・')}消失`}));const rows=[...conditional,...losses];if(!rows.length)return '';const keywords=[...new Set(rows.flatMap(row=>row.keywords))];return `<div class="detail-identity-conditions"><div class="detail-identity-condition-head"><b>条件付き</b><span>${keywords.map(keyword=>`<i data-keyword="${esc(keyword)}">${esc(keyword)}</i>`).join('')}</span></div><div class="detail-identity-condition-rows">${rows.map(row=>`<small>● ${esc(row.text)}</small>`).join('')}</div></div>`};
 const identities=selectedParty.map(x=>{const image=window.LimbusIdentityImages?.forIdentity?.(x.sinner,x.identity,{free:isFreeIdentity(x)});const conditions=identityConditionMarkup(x);return `<article class="detail-identity-card ${isFreeIdentity(x)?'is-free':''}${image?' has-identity-image':''}${conditions?' has-conditions':''}"${image?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.02) 0%,rgba(0,0,0,.18) 42%,rgba(0,0,0,.9) 100%),url('${esc(image)}')"`:''}><span>${esc(sinnerNumber(x))}</span><div class="detail-identity-card-copy"><strong>${esc(x.sinner)}</strong><small>${esc(isFreeIdentity(x)?'自由枠（誰でも可）':normalizeLegacyIdentityName(x.identity))}</small>${conditions}</div></article>`;}).join('');
 const alternatives=selectedParty.filter(x=>(x.alternatives||[]).length).map(x=>`<article class="detail-substitute-group"><b>${esc(sinnerNumber(x))} ${esc(x.sinner)}の代用</b><div class="detail-substitute-cards">${x.alternatives.map(name=>{const normalized=normalizeLegacyIdentityName(name);const image=window.LimbusIdentityImages?.forIdentity?.(x.sinner,normalized,{free:false});return `<span class="detail-substitute-card${image?' has-identity-image':''}"${image?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.84)),url('${esc(image)}')"`:''}>${esc(normalized)}</span>`;}).join('')}</div></article>`).join('');
 const formation=[...(post.party||[])].sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)).map(x=>{const image=window.LimbusIdentityImages?.forIdentity?.(x.sinner,x.identity,{free:isFreeIdentity(x)});return `<article class="detail-party-card ${isFreeIdentity(x)?'is-free':''}${image?' has-identity-image':''}"${image?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.88)),url('${esc(image)}')"`:''}><span>${String(x.order||'--').padStart(2,'0')}</span><strong>${esc(x.sinner)}</strong><small>${esc(isFreeIdentity(x)?'自由枠（誰でも可）':normalizeLegacyIdentityName(x.identity))}</small></article>`;}).join('');
 const egoRankClass=rank=>`rank-${String(rank||'').trim().toLowerCase()}`;
 const egoItemMarkup=item=>{const raw=String(item??'').trim();const match=raw.match(/^(ZAYIN|TETH|HE|WAW|ALEPH)\s*[：:]\s*(.+)$/i);const rank=(match?.[1]||'').toUpperCase(),name=match?.[2]||raw;return `<span class="review-ego-tag ${egoRankClass(rank)}"><b>${esc(rank||'E.G.O')}</b><span class="review-ego-name">${esc(name)}</span></span>`;};
 const egos=(post.egos||[]).length?post.egos.map(g=>`<article class="detail-ego-card"><strong>${esc(g.sinner)}</strong><div class="review-card-ego-list">${(g.items||[]).map(egoItemMarkup).join('')||'<span class="review-ego-empty">未選択</span>'}</div></article>`).join(''):'<p class="detail-empty">使用E.G.Oは設定されていません。</p>';
 const packs=(post.themePacks||[]).length?[...post.themePacks].sort((a,b)=>(Number(a.floor)||999)-(Number(b.floor)||999)).map(x=>{const name=window.LimbusThemePackNames?.canonical?.(x.name)||x.name;const image=window.LimbusThemePackImages?.forName(name,post.difficulty)||'';return `<article class="theme-pack-option-card detail-pack-option has-pack-image selected">${image?`<span class="theme-pack-image-frame"><img src="${esc(image)}" alt="" loading="lazy"></span>`:`<span class="theme-pack-image-frame theme-pack-image-placeholder" aria-hidden="true"><b>${name==='自由枠'?'FREE':'NO IMAGE'}</b></span>`}<strong>${esc(name)}</strong><small>${esc(x.floor)}Fで選択</small></article>`;}).join(''):'<p class="detail-empty">進行テーマパックは設定されていません。</p>';
 const formationCodeSection=`<section class="detail-section detail-formation-code"><div class="detail-section-title"><small>FORMATION CODE</small><h2>編成コード</h2></div><textarea data-detail-formation-code readonly rows="4" aria-label="この投稿の編成コード">生成中…</textarea><div class="detail-formation-code-actions"><p data-detail-formation-code-status>使用方法が分からない方は最下の<a href="#formation-code-guide">「編成コードの使い方」</a>をチェック</p><button class="button button-primary" data-copy-detail-formation-code type="button" disabled>編成コードをコピー</button></div></section>`;
 const formationGuideSection=`<details class="detail-section formation-code-guide" id="formation-code-guide"><summary><span><small>FORMATION CODE GUIDE</small><strong>編成コードの使い方</strong></span><b aria-hidden="true">＋</b></summary><div class="formation-guide-body"><div class="formation-guide-copy"><h3>編成コードとは？</h3><p>編成コードは、Limbus Companyの編成情報を共有するための機能です。</p><p>ゲーム内で発行した編成コードを入力すると、人格やE.G.O.などの編成内容を自動で読み込み、このサイトの投稿作成画面へ反映できます。</p><p>また、このサイトで作成した編成からも編成コードを生成できます。生成されたコードをゲーム内で読み込むことで、投稿されている編成を簡単に再現できます。</p></div><div class="formation-guide-steps"><h3>編成コードの取得方法</h3><ol><li><img src="assets/formation-code-guide/01-formation-screen.png" alt="Limbus Companyの編成画面" loading="lazy"><span><b>1</b><strong>Limbus Companyの編成画面を開く</strong></span></li><li><img src="assets/formation-code-guide/02-issue-button.png" alt="編成コード発行ボタンの位置" loading="lazy"><span><b>2</b><strong>編成コード発行ボタンを選択する</strong></span></li><li><img src="assets/formation-code-guide/03-code-dialog.png" alt="ゲーム内の編成コード表示画面" loading="lazy"><span><b>3</b><strong>表示された編成コードをコピーする</strong></span></li></ol></div><div class="formation-guide-features"><h3>このサイトでできること</h3><ul><li>ゲーム内の編成を投稿画面へ自動入力</li><li>投稿された編成をゲーム内で再現</li><li>編成コードをワンクリックでコピー</li><li>手入力不要で編成共有</li></ul></div><div class="formation-guide-notes"><p>※所持していない人格やE.G.O.が含まれている場合、ゲーム内で編成を完全に再現できないことがあります。</p><p>※アップデートにより編成コードの仕様が変更された場合、一部機能が正常に動作しないことがあります。</p></div></div></details>`;
 root.innerHTML=`<article class="post-detail-article"><header class="post-detail-hero"><div class="detail-badges"><span>${esc(post.category)}</span><span>${esc(post.difficulty)}</span><span>${esc(post.type)}</span></div><div class="detail-title-row"><div><p class="section-kicker">STRATEGY DETAIL</p><h1>${esc(post.title)}</h1></div></div><p class="post-detail-summary">${esc(post.summary)}</p><div class="detail-author-card">${api.authorMarkup(profile)}<a class="post-detail-link" href="${profile.id==='admin-m'?'index.html#community':`profile.html?id=${encodeURIComponent(profile.id)}`}">投稿者を見る</a></div><div class="detail-meta"><span>閲覧 ${Number(post.views||0).toLocaleString('ja-JP')}</span><button type="button" class="detail-like-button" data-detail-like><span aria-hidden="true">♥</span><b data-detail-like-count>${Number(post.likes||0).toLocaleString('ja-JP')}</b></button><span>投稿日 ${String(post.published||'').slice(0,10)}</span></div><div class="detail-tag-row">${[...(post.keywords||[]),...(post.tags||[])].map(x=>`<span>${esc(x)}</span>`).join('')}</div></header>${formationCodeSection}<section class="detail-section"><div class="detail-section-title"><small>SELECTED IDENTITIES</small><h2>使用人格</h2></div><div class="detail-identity-grid">${identities}</div></section>${alternatives?`<section class="detail-section"><div class="detail-section-title"><small>SUBSTITUTE IDENTITIES</small><h2>代用人格 <em>任意</em></h2></div><div class="detail-substitute-grid">${alternatives}</div></section>`:''}<section class="detail-section"><div class="detail-section-title"><small>PARTY ORDER</small><h2>編成順</h2></div><div class="detail-party-grid">${formation}</div></section><section class="detail-section"><div class="detail-section-title"><small>E.G.O</small><h2>装備E.G.O</h2></div><div class="detail-ego-grid">${egos}</div></section><section class="detail-section"><div class="detail-section-title"><small>THEME PACK ROUTE</small><h2>選択パック</h2></div><div class="detail-pack-list">${packs}</div></section><section class="detail-section detail-description"><div class="detail-section-title"><small>STRATEGY</small><h2>攻略説明</h2></div><p>${esc(post.description||'').replaceAll('\n','<br>')}</p></section></article>`;
 root.insertAdjacentHTML('beforeend',formationGuideSection);
 const guide=document.querySelector('#formation-code-guide');document.querySelectorAll('a[href="#formation-code-guide"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();guide.open=true;guide.scrollIntoView({behavior:'smooth',block:'start'})}));guide?.addEventListener('toggle',()=>{const icon=guide.querySelector('summary>b');if(icon)icon.textContent=guide.open?'−':'＋'});
 const detailBadges=document.querySelector('.detail-badges');if(detailBadges){const seasonBadge=document.createElement('span');seasonBadge.className='detail-season-badge';seasonBadge.textContent=`SEASON ${post.season||7}`;detailBadges.prepend(seasonBadge);}
 const keywordSet=new Set((post.keywords||[]).map(value=>String(value).trim()));document.querySelectorAll('.detail-tag-row span').forEach(tag=>{const keyword=tag.textContent.trim();if(keywordSet.has(keyword))tag.dataset.keyword=keyword;});
 const formationOutput=document.querySelector('[data-detail-formation-code]'),formationStatus=document.querySelector('[data-detail-formation-code-status]'),formationCopy=document.querySelector('[data-copy-detail-formation-code]');let formationCode='';
 try{const response=await fetch('data/game-id-map.json');if(!response.ok)throw new Error('mapping');const map=await response.json();const formationPost={...post,selectedIdentities:(post.selectedIdentities||[]).map(item=>({...item,identity:normalizeLegacyIdentityName(item.identity)})),party:(post.party||[]).map(item=>({...item,identity:normalizeLegacyIdentityName(item.identity)}))};const slots=window.LimbusFormationCode.slotsFromContent(formationPost,map);formationCode=await window.LimbusFormationCode.encode(slots);formationCopy.disabled=false;}catch(codeError){console.error('編成コードを生成できませんでした。',codeError);formationOutput.value='';formationStatus.textContent='この投稿の編成コードを生成できませんでした。';}
 formationCopy?.addEventListener('click',async()=>{if(!formationCode)return;try{await navigator.clipboard.writeText(formationCode);}catch{formationOutput.focus();formationOutput.select();document.execCommand('copy');}showToast('編成コードをコピーしました。');});
 const likeButton=document.querySelector('[data-detail-like]'),likeCount=document.querySelector('[data-detail-like-count]');
 const syncLike=async()=>{const liked=await api.isLiked(post.id);likeButton?.classList.toggle('is-liked',liked);likeButton?.setAttribute('aria-pressed',String(liked));likeButton?.setAttribute('aria-label',liked?'いいねを取り消す':'この攻略にいいねする');};
 await syncLike();if(likeButton)likeButton.onclick=async()=>{const user=await api.sessionUser();if(!user){window.LimbusAuth?.open();return;}likeButton.disabled=true;try{const liked=likeButton.classList.contains('is-liked');const total=await api.setLike(post.id,!liked);likeCount.textContent=Number(total||0).toLocaleString('ja-JP');await syncLike();}finally{likeButton.disabled=false;}};
 const buttons=[...document.querySelectorAll('[data-save-post]')];const currentUser=await api.sessionUser();const ownPost=currentUser?.id===cloud?.author_id;if(ownPost)buttons.forEach(btn=>{btn.disabled=true;btn.classList.add('is-own-post');btn.textContent='🔖 自分の投稿';btn.title='自分の投稿はブックマークできません';});const sync=async()=>{if(ownPost)return;const saved=await api.isBookmarked(post.id);buttons.forEach(btn=>{btn.classList.toggle('is-saved',saved);btn.setAttribute('aria-pressed',String(saved));btn.textContent=saved?'🔖 保存済み':'🔖 ブックマーク'})};await sync();buttons.forEach(btn=>btn.onclick=async()=>{if(ownPost)return;const user=await api.sessionUser();if(!user){window.LimbusAuth?.open();return}const saved=await api.isBookmarked(post.id);await api.setBookmark(post.id,!saved);await sync();showToast(saved?'ブックマークを解除しました。':'ブックマークに保存しました。')});
 const reportButtons=[...document.querySelectorAll('[data-open-report]')],reportDialog=document.querySelector('[data-report-dialog]'),reportForm=document.querySelector('[data-report-form]'),reportStatus=document.querySelector('[data-report-status]');
 if(ownPost)reportButtons.forEach(button=>button.hidden=true);
 const closeReport=()=>{if(!reportDialog)return;reportDialog.classList.remove('is-open');document.body.classList.remove('dialog-open','report-dialog-open');setTimeout(()=>reportDialog.hidden=true,180)};
 const openReport=async()=>{const user=await api.sessionUser();if(!user){window.LimbusAuth?.open();return;}if(ownPost){showToast('自分の投稿は通報できません。');return;}if(!reportDialog)return;reportStatus.hidden=true;reportStatus.textContent='';reportDialog.hidden=false;requestAnimationFrame(()=>reportDialog.classList.add('is-open'));document.body.classList.add('dialog-open','report-dialog-open');};
 reportButtons.forEach(button=>button.addEventListener('click',openReport));document.querySelectorAll('[data-close-report]').forEach(btn=>btn.addEventListener('click',closeReport));reportDialog?.addEventListener('click',e=>{if(e.target===reportDialog)closeReport()});if(params.get('report')==='1'){const nextUrl=new URL(location.href);nextUrl.searchParams.delete('report');history.replaceState(null,'',`${nextUrl.pathname}${nextUrl.search}${nextUrl.hash}`);openReport();}
 reportForm?.addEventListener('submit',async e=>{e.preventDefault();const submit=reportForm.querySelector('[data-submit-report]');const reason=reportForm.reason.value,details=reportForm.details.value.trim();if(!reason)return;submit.disabled=true;reportStatus.hidden=true;try{await api.submitReport(post.id,reason,details);reportForm.reset();closeReport();showToast('通報を送信しました。管理者が確認します。');reportButtons.forEach(button=>{button.disabled=true;button.textContent='⚑ 通報済み';});}catch(error){console.error(error);const message=String(error?.message||'');reportStatus.textContent=message.includes('already-reported')?'この投稿はすでに通報済みです。':message.includes('own-post-report')?'自分の投稿は通報できません。':message.includes('relation "reports" does not exist')||message.includes('Could not find the table')?'通報機能のデータベース設定がまだ完了していません。':'通報を送信できませんでした。時間をおいて再度お試しください。';reportStatus.dataset.state='error';reportStatus.hidden=false;}finally{submit.disabled=false;}});
 const shareDialog=document.querySelector('[data-share-dialog]'),openShare=()=>{shareDialog.hidden=false;requestAnimationFrame(()=>shareDialog.classList.add('is-open'));document.body.classList.add('dialog-open')},closeShare=()=>{shareDialog.classList.remove('is-open');document.body.classList.remove('dialog-open');setTimeout(()=>shareDialog.hidden=true,180)};document.querySelector('[data-open-share]')?.addEventListener('click',openShare);document.querySelector('[data-close-share]')?.addEventListener('click',closeShare);shareDialog?.addEventListener('click',e=>{if(e.target===shareDialog)closeShare()});const shareUrl=location.href,shareText=`${post.title}｜Limbus Company 攻略投稿サイト`;document.querySelector('[data-share-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(shareUrl);closeShare();showToast('URLをコピーしました。')});document.querySelector('[data-share-x]')?.addEventListener('click',()=>window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,'_blank','noopener,noreferrer'));document.querySelector('[data-share-bluesky]')?.addEventListener('click',()=>window.open(`https://bsky.app/intent/compose?text=${encodeURIComponent(`${shareText}\n${shareUrl}`)}`,'_blank','noopener,noreferrer'));
}catch(error){console.error(error);root.innerHTML='<section class="detail-error"><h1>投稿を表示できませんでした</h1><p>投稿が存在しないか、閲覧権限がありません。</p><a class="button button-primary" href="index.html#community">投稿一覧へ戻る</a></section>'}
})();
