import {htmlEscape,identityImageMap,postMeta,selectedIdentities} from './og-data.js';

export async function buildOgCardHtml(post,profile,origin){
  const meta=postMeta(post,profile),identities=selectedIdentities(post),images=await identityImageMap(origin);
  const cells=Array.from({length:12},(_,index)=>{
    const item=identities[index];
    if(!item)return `<div class="cell empty"><b>${String(index+1).padStart(2,'0')}</b></div>`;
    const key=String(item.identity||'').includes('自由枠')?'自由枠':item.identity;
    const src=images.get(`${item.sinner}\u0000${key}`)||'';
    return `<div class="cell"${src?` style="background-image:linear-gradient(180deg,rgba(0,0,0,.03),rgba(0,0,0,.1) 45%,rgba(0,0,0,.92)),url('${htmlEscape(src)}')"`:''}><b>${String(index+1).padStart(2,'0')}</b><span>${htmlEscape(item.sinner)}</span><small>${htmlEscape(item.identity)}</small></div>`;
  }).join('');
  const chips=[`SEASON ${meta.season}`,meta.category,meta.difficulty].filter(Boolean).map(value=>`<span>${htmlEscape(value)}</span>`).join('');
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1200px;height:630px;overflow:hidden;background:#12161d;color:#fff;font-family:"Yu Gothic","Hiragino Kaku Gothic ProN",sans-serif}.card{width:1200px;height:630px;padding:26px 30px;background:radial-gradient(circle at 82% 14%,rgba(215,159,32,.16),transparent 31%),linear-gradient(135deg,#11161d,#1b2028);border:2px solid #bd8b20}.head{height:112px;display:grid;grid-template-columns:1fr auto;gap:24px;align-items:center}.eyebrow{color:#e6b743;font:700 15px Georgia,serif;letter-spacing:.25em}.title{font:700 33px Georgia,"Yu Mincho",serif;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:830px;margin-top:9px}.chips{display:flex;gap:8px;justify-content:flex-end;align-items:center}.chips span{border:1px solid #c99729;color:#f3d176;background:#211c13;padding:8px 12px;font-weight:800;font-size:14px}.grid{display:grid;grid-template-columns:repeat(6,1fr);grid-template-rows:repeat(2,211px);gap:8px}.cell{position:relative;overflow:hidden;border:1px solid #806522;background:#252a31 center/cover no-repeat;box-shadow:inset 0 0 0 1px rgba(255,255,255,.05)}.cell b{position:absolute;left:9px;top:8px;font:800 16px Georgia,serif;text-shadow:0 2px 3px #000}.cell span{position:absolute;left:10px;right:8px;bottom:31px;font-weight:900;font-size:19px;text-shadow:0 2px 4px #000}.cell small{position:absolute;left:10px;right:8px;bottom:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:700;font-size:12px;text-shadow:0 2px 3px #000}.empty{background:linear-gradient(135deg,#1c2128,#252a31);border-style:dashed}.foot{height:44px;display:flex;justify-content:space-between;align-items:end;color:#d2c8b4;font-size:14px}.brand{color:#efc65b;font:700 18px Georgia,serif;letter-spacing:.12em}.author{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:560px}</style></head><body><main class="card"><header class="head"><div><div class="eyebrow">LIMBUS COMPANY STRATEGY</div><div class="title">${htmlEscape(meta.title)}</div></div><div class="chips">${chips}</div></header><section class="grid">${cells}</section><footer class="foot"><span class="author">投稿者 ${htmlEscape(meta.author)}</span><strong class="brand">LIMBUS COMPANY 攻略投稿サイト</strong></footer></main></body></html>`;
}
